CREATE TABLE info (`NAME ` VARCHAR(30) NOT NULL,
  money INT,
  item1 TINYINT DEFAULT FALSE,
  item2 TINYINT DEFAULT FALSE
)


CREATE TABLE `game`.`info` (
` ID ` INT NOT NULL AUTO_INCREMENT COMMENT '',
` NAME ` VARCHAR(45) NOT NULL COMMENT '',
` MONEY ` INT NULL COMMENT '',
`item1` TINYINT DEFAULT FALSE,
`item2` TINYINT DEFAULT FALSE,
PRIMARY KEY (` ID `)  COMMENT '');
